# Generated by Django 5.0 on 2024-01-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_careerapplication_delete_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerapplication',
            name='file',
            field=models.FileField(null=True, upload_to='career_applications/'),
        ),
        migrations.AlterField(
            model_name='careerapplication',
            name='text',
            field=models.DateField(null=True),
        ),
    ]
